# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
