# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171129_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_custom',
            new_name='date_publish',
        ),
    ]
